FROM postgis/postgis:15-3.4 AS runtime

LABEL maintainer="Lars Wilhelmsen <lars@sral.org>" \
    org.opencontainers.image.description="PostGIS 3.4.2+dfsg-1.pgdg110+1 spatial database extension AND accumulo_access_pg with PostgreSQL 15 bullseye" \
    org.opencontainers.image.source="https://github.com/larsw/accumulo_access_pg"

ADD out/accumulo_access_bullseye_pg15_0.1.0_amd64.deb /tmp/
RUN mkdir -p /docker-entrypoint-initdb.d && apt install -y /tmp/accumulo_access_bullseye_pg15_0.1.0_amd64.deb
ADD 10_accumulo_access.sh /docker-entrypoint-initdb.d/
