# syntax=docker/dockerfile:1
#
# Plain PostgreSQL + accumulo_access_pg.
#
#   docker build -f Dockerfile.postgres -t <tag> .                    # PG 18
#   docker build -f Dockerfile.postgres -t <tag> \                    # PG 19 beta
#     --build-arg BASE_IMAGE=postgres:19beta3-trixie --build-arg PG_MAJOR=19 .
#
# Expects the matching .deb from `Dockerfile.build` to be in ./out.
ARG BASE_IMAGE=postgres:18.6-trixie

FROM ${BASE_IMAGE} AS runtime

ARG PG_MAJOR=18

LABEL maintainer="Lars Wilhelmsen <lars@sral.org>" \
    org.opencontainers.image.description="PostgreSQL ${PG_MAJOR} with the accumulo_access_pg database extension" \
    org.opencontainers.image.source="https://github.com/larsw/accumulo-access-pg"

COPY out/accumulo_access_*_pg${PG_MAJOR}_*_amd64.deb /tmp/ext/
RUN dpkg --install /tmp/ext/*.deb && rm -rf /tmp/ext

# Sourced (not executed) by docker-entrypoint.sh, so it must stay non-executable.
COPY 10_accumulo_access.sh /docker-entrypoint-initdb.d/
